spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_profile
    username: root
    password: arun123123 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

